### ISSUE TITLE
[Feature] UpdatePolicy

### ISSUE THREAD

**Issue by amshuman-kr** [gardener/hvpa-controller#13]
**Feature (What you would like to be added):**
We should introduce the `UpdatePolicy` functionality along the similar lines to the `UpdatePolicy` functionality in [VPA](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1beta2/types.go#L80).

**Motivation (Why is this needed?):**
1. This will help us roll out HVPA conservatively in `Off` mode, monitor the quantity/increment/frequency of scaling by HVPA before switching it on.

1. It can also help in debugging for developers and operators in case of abnormal behaviour by supporting a quick way to switch of the scaling by HVPA without having to delete the HVPA resource.
 
**Approach/Hint to the implement solution (optional):**
1. The update mode could be an enumeration. For example, `Off`, `On`, `ScaleUp`.

**Comment by ggaurav10** [comment]
In `off` mode, HVPA may not be able to deploy/create HPA as it can not be deployed in "off" mode as of now. We can still deploy VPA in "off" mode though. I can go ahead and implement this, however, I am not sure how much of value addition it is until HPA supports "off" mode. WDYT?

**Comment by amshuman-kr** [comment]
How about moving the update mode into the HPA and VPA sub-sections?

**Comment by ggaurav10** [comment]
Yes, makes sense to include the mode at both levels. In fact, we can have this per-container level too for VPA part.
About "off" mode for HVPA as a whole - we may not be able to deploy HPA at all as of now. I can go ahead with this implementation, however, I am not sure how much value addition it is until HPA supports "off" mode. WDYT?

**Comment by ggaurav10** [comment]
As discussed offline with @amshuman-kr, for now we will not deploy HPA when HVPA or HPA is in "off" mode.

**Comment by amshuman-kr** [comment]
The more I think, it might be better to support the updatePolicy/Mode at the lower levels only and avoid the global updatePolicy/mode.

Something like
```
apiVersion: ...
kind: HVPA
metadata: {}
spec:
  hvpaTemplate:
    metadata: {}
    spec:
      updatePolicy: Off/On/ScaleOut
      ...
  vpaTemplate:
    metadata: {}
    spec:
      updatePolicy:
        updateMode: Off/On/ScaleUp
      resourcePolicy:
        containerPolicies:
        - containerName: ...
           mode: On/Off
```

**Comment by ggaurav10** [comment]
Does `selector` need to be included separately under HPA and VPA? Shouldn't it be common for both?

**Comment by amshuman-kr** [comment]
> Does selector need to be included separately under HPA and VPA? Shouldn't it be common for both?

We can mix them. But then what about the templates (both metadata and spec)? How would those look like?

It looks cleaner if we keep the templates and the selectors for HPA and VPA separate, don't you think?

**Comment by ggaurav10** [comment]
IMO, we should keep the common fields common instead of separate to avoid duplications. This also eliminates chances of users mentioning different details by mistake.

>But then what about the templates (both metadata and spec)? 

They can still be as mentioned by you in the hvpa spec because metadata and spec can anyway be different for HPA and VPA. However, do we really need the field `metadata`? Should we allow users to still manipulate the metadata fields of HPA and VPA if we plan to abstract them into HVPA?
WDYT?

**Comment by amshuman-kr** [comment]
Let's introduce the updatePolicy value `Purge` to both `HpaUpdatePolicy` and `VpaUpdatePolicy` to indicate that the corresponding HPA and VPA resources should be no created (or cleaned up if they were already created).

Something like below...
```yaml
apiVersion: ...
kind: HVPA
metadata: {}
spec:
  hpa:
    selector:
    updatePolicy: Purge/Off/Auto/ScaleOut
    template:
      metadata: {}
      spec:
        ...
  vpa:
    selector:
    updatePolicy: Purge/Off/Auto/ScaleUp
    template:
      metadata: {}
      spec:        
        resourcePolicy:
          containerPolicies:
          - containerName: ...
             mode: On/Auto
```
